download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/ansible-eda-2.6.1.tar.gz
format_version: 1.0.0
name: eda
namespace: ansible
server: https://console.redhat.com/api/automation-hub/content/published/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2025-03-31T16:30:14.269929Z'
  signature: '-----BEGIN PGP SIGNATURE-----

    Version: GnuPG v1


    iQIcBAABCAAGBQJn6sMLAAoJEOGkvXCKgoqtaIUP/RreIKIMA+N8tioIDvPXZvg6

    0r3jhbaPPSgEf7F5RZI6xUBLyRHX0wz5Oicz9vSSBMNRAyLIrpkZH1+ciLnW9wtT

    lWs5k2FXAJ1aYnYNV/10S9TPfLF6HVk2tsqI+0Y0514vFCyK+fCa79GwxMXqA5o2

    gHCvrjxhtwNn8NQiLGypl7K47hD4+wkeAir+4pGBWppIxuLHInL+90sFSN8q5eIC

    sWBUcFqCTdzdKQLoIzk/Y2h1E9RG4bsfqYCSSTuZGMwVssIrZujz84NOPKPL4st1

    GtHEE5w93vwOyEB1NfawLaBufhIg9Ywbyip8E/+XxZuVQGuOrgIdfHguS9ueA6vK

    XYgXiys+6ui1i0QOtJg+ibUc6/uGqjPmCpsKnbFF6Vj98BLyCjj+7W2OohgK9DkJ

    WPalX9Gmtcu7DFfucVwPUDGRnMwJujhFkaoMY+JgAj18RNivcggrTYNAWKTwWdYX

    iYrWbUfEwIBqul6U7XIUtJXRg86OmUabrwybW2CO6XElNwpgIG/OFDOrjy1glxwl

    CVMyGqbaMgRNiFTI6R2QcAPstbsIhg2m8qfwYA0TTq0wRgBx1ox23M56/vfGhsTr

    +CpezjjfQpindD8+KIq/Wmv1XC/ebAVO6qtKPHh1xgXcECIuFWBOlpzqh+9eLPZM

    KpldJ10bmZtDVAhliPsD

    =RkDK

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 2.6.1
version_url: /api/automation-hub/content/published/v3/plugin/ansible/content/published/collections/index/ansible/eda/versions/2.6.1/
